version: '3.4'

services:
  newsletter-db:
    image: postgres:latest
    container_name: Newsletter.PostgresDB
    volumes:
      - ./.containers/postgres/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - 5432:5432

  newsletter-mq:
    image: rabbitmq:management
    container_name: Newsletter.RabbitMq
    hostname: newsletter-mq
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  newsletter.api:
    image: ${DOCKER_REGISTRY-}newsletterapi
    container_name: Newsletter.Api
    build:
      context: .
      dockerfile: NewsLetter.Api/Dockerfile
    depends_on:
      newsletter-mq:
        condition: service_healthy
      newsletter-db:
        condition: service_started

  newsletterreporting.api:
    image: ${DOCKER_REGISTRY-}newsletterreportingapi
    container_name: Newsletter.ReportingApi
    build:
      context: .
      dockerfile: NewsLetterReporting.Api/Dockerfile
    depends_on:
      newsletter-mq:
        condition: service_healthy
      newsletter-db:
        condition: service_started

  newsletter.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: Newsletter.Dashboard
    ports:
      - 18888:18888

